# Generated by Django 4.0.2 on 2022-02-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeMachines',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('1', 'COFFEE_MACHINE_LARGE'), ('2', 'COFFEE_MACHINE_SMALL'), ('3', 'ESPRESSO_MACHINE')], max_length=50)),
                ('water_line_compatible', models.BooleanField()),
                ('model_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CoffePods',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('1', 'COFFEE_POD_LARGE'), ('2', 'COFFEE_POD_SMALL'), ('3', 'ESPRESSO_POD')], max_length=50)),
                ('coffe_flavor', models.CharField(choices=[('1', 'COFFEE_FLAVOR_VANILLA'), ('2', 'COFFEE_FLAVOR_CARAMEL'), ('3', 'COFFEE_FLAVOR_PSL'), ('4', 'COFFEE_FLAVOR_MOCHA'), ('5', 'COFFEE_FLAVOR_HAZELNUT')], max_length=50)),
                ('pack_size', models.IntegerField(choices=[('1', '1'), ('2', '3'), ('3', '5'), ('4', '7')])),
            ],
        ),
    ]
