# Generated by Django 4.0.2 on 2022-02-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffemachines',
            options={'verbose_name_plural': 'Coffe Machines'},
        ),
        migrations.AlterModelOptions(
            name='coffepods',
            options={'verbose_name_plural': 'Coffe Pods'},
        ),
    ]
