# Generated by Django 4.0.2 on 2022-02-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_coffemachines_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffepods',
            name='pack_size',
            field=models.CharField(choices=[('1', '1 dozen (12)'), ('2', '3 dozen (36)'), ('3', '5 dozen (60)'), ('4', '7 dozen (84)')], max_length=50),
        ),
    ]
