# Generated by Django 4.0.2 on 2022-02-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_coffepods_pack_size'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='coffemachines',
            order_with_respect_to='id',
        ),
        migrations.AlterOrderWithRespectTo(
            name='coffepods',
            order_with_respect_to='id',
        ),
    ]
