# Generated by Django 4.0.2 on 2022-02-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_coffemachines_order_with_respect_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffemachines',
            options={'ordering': ['id'], 'verbose_name_plural': 'Coffe Machines'},
        ),
        migrations.AlterModelOptions(
            name='coffepods',
            options={'ordering': ['id'], 'verbose_name_plural': 'Coffe Pods'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='coffemachines',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='coffepods',
            order_with_respect_to=None,
        ),
    ]
