# Generated by Django 4.0.2 on 2022-03-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_coffebeans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffebeans',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='coffebeans',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
