# Generated by Django 4.0.2 on 2022-03-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_coffebeans_capacity_alter_coffebeans_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffebeans',
            name='pack_size',
        ),
    ]
