# Generated by Django 4.0.2 on 2022-03-07 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_delete_coffebeans_coffepods_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeBeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'Coffe Beans',
            },
        ),
        migrations.RemoveField(
            model_name='coffepods',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='coffepods',
            name='quantity',
        ),
    ]
