# Generated by Django 4.0.2 on 2022-03-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_coffebeans_remove_coffepods_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffebeans',
            name='quantity',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
