# Generated by Django 3.2.12 on 2022-03-13 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_coffebeans_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffebeans',
            name='name',
            field=models.CharField(default='Brazilian_Beans', max_length=50),
        ),
        migrations.AddField(
            model_name='coffepods',
            name='beans_type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='store.coffebeans'),
            preserve_default=False,
        ),
    ]
